%% 空间衍架结构——【单元坐标系】下【杆件单元】的刚度
%% 输入：杆件在单元中的编号
%% 输出：杆件节点的刚度[6*6的矩阵]
function M_Rod = SpaceFrame_MassMatrix_Rod(NUM_Cell_Rod)

global Ax Inertia_moment Density  
global Coordinate_Cell_Node Coordinate_Cell_Rod

%% 杆件节点坐标及坐标变换矩阵
NUM_Node = Coordinate_Cell_Rod(NUM_Cell_Rod,:);     % 读取杆件编号所对应杆的节点编号
pj = Coordinate_Cell_Node(NUM_Node(1),:) ;        % 杆件的节点坐标读取
pk = Coordinate_Cell_Node(NUM_Node(2),:) ;        % 杆件的节点坐标读取
% pj = Coordinate_Cell_Node(NUM_Node(1),:) + Displacement_i(6*NUM_Node(1)-5:6*NUM_Node(1)-3);        % 杆件的节点坐标读取
% pk = Coordinate_Cell_Node(NUM_Node(2),:) + Displacement_i(6*NUM_Node(2)-5:6*NUM_Node(2)-3);        % 杆件的节点坐标读取
xm = pk - pj; %xm轴的方向向量(横向量)
L  =  norm(xm);

c = sqrt(xm(1)^2+xm(3)^2);
if c > 0.0001
    zm = [-xm(3) 0 xm(1);];  % 倾斜杆件zm轴的方向向量
else
    zm = [0 0 1;];           % 垂直杆件zm轴的方向向量
end
ym = cross(zm,xm);           % ym轴的方向向晕
R =[xm/norm(xm); ym/norm(ym); zm/norm(zm);]; %转轴矩阵

RT = [     R      zeros(3)     zeros(3)     zeros(3);...
       zeros(3)      R         zeros(3)     zeros(3);...
       zeros(3)   zeros(3)        R         zeros(3);...
       zeros(3)   zeros(3)     zeros(3)        R    ;];

Rhoi = Density;
Ix= Inertia_moment(1,1);
Iy= Inertia_moment(2,1);
Iz= Inertia_moment(3,1);
Ax_i=Ax;
%% 杆件质量矩阵
%% Euler-Bernoulli 梁
M_Rod =Rhoi*Ax*L/420* [140    0      0         0          0         0      70      0      0         0           0        0    ;...
                          0    156     0         0          0        22*L     0      54     0         0           0      -13*L  ;...
                          0     0     156        0       -22*L        0       0      0     54         0         13*L       0    ;...
                          0     0      0    140*Ix/Ax     0         0       0      0      0     70*Ix/Ax      0        0    ;...
                          0     0    -22*L       0        4*L^2       0       0      0    -13*L       0        -3*L^2      0    ;...
                          0   22*L     0         0          0       4*L^2     0    13*L     0         0           0     -3*L^2  ;...
                         70     0      0         0          0         0      140     0      0         0           0        0    ;...
                          0    54      0         0          0       13*L      0     156     0         0           0      -22*L  ;...
                          0     0     54         0        -13*L       0       0      0     156        0         22*L       0    ;...
                          0     0      0     70*Ix/Ax     0         0       0      0      0     140*Ix/Ax     0        0    ;...
                          0     0     13*L       0        -3*L^2      0       0      0     22*L       0         4*L^2      0    ;...
                          0   -13*L    0         0          0      -3*L^2     0   -22*L     0         0           0      4*L^2  ;];

%% 瑞丽梁
% M_ii = [ 1/3              0                        0                    0                0                           0              ;...
%           0    13/35+6*Iz/(5*Ax*L^2)             0                    0                0                  11*L/210+Iz/(10*Ax*L) ;...
%           0               0              13/35+6*Iy/(5*Ax*L^2)        0      -(11*L/210+Iy/(10*Ax*L))             0              ;...
%           0               0                        0               Ix/3/Ax             0                           0              ;...
%           0               0             -(11*L/210+Iy/(10*Ax*L))      0       L^2/105+2*Iy/15/Ax                 0              ;...
%           0     11*L/210+Iz/(10*Ax*L)            0                    0                0                 L^2/105+2*Iz/15/Ax     ;];
% 
% M_jj = [ 1/3              0                        0                    0                0                           0                 ;...
%           0    13/35+6*Iz/(5*Ax*L^2)             0                    0                0                -(11*L/210+Iz/(10*Ax*L))   ;...
%           0               0              13/35+6*Iy/(5*Ax*L^2)        0      (11*L/210+Iy/(10*Ax*L))              0                ;...
%           0               0                        0               Ix/3/Ax             0                            0                ;...
%           0               0              (11*L/210+Iy/(10*Ax*L))      0       L^2/105+2*Iy/15/Ax                  0                ;...
%           0   -(11*L/210+Iz/(10*Ax*L))           0                    0                0                  L^2/105+2*Iz/15/Ax       ;];
% 
% 
% M_ij = [ 1/6              0                         0                       0                 0                         0              ;...
%           0    9/70+6*Iz/(5*Ax*L^2)               0                       0                 0              -13*L/420+Iz/(10*Ax*L)  ;...
%           0               0                9/70-6*Iy/(5*Ax*L^2)           0       13*L/420-Iy/(10*Ax*L)             0              ;...
%           0               0                         0                  Ix/6/Ax              0                         0              ;...
%           0               0               -13*L/420+Iy/(10*Ax*L)          0       -L^2/140-Iy/30/Ax                 0              ;...
%           0     13*L/420-Iz/(10*Ax*L)             0                       0                 0                -L^2/140-Iz/30/Ax     ;];
% 
% M_ji = [ 1/6              0                         0                       0                 0                         0              ;...
%           0    9/70+6*Iz/(5*Ax*L^2)               0                       0                 0               13*L/420-Iz/(10*Ax*L)  ;...
%           0               0                9/70-6*Iy/(5*Ax*L^2)           0      -13*L/420+Iy/(10*Ax*L)             0              ;...
%           0               0                         0                  Ix/6/Ax              0                         0              ;...
%           0               0                13*L/420-Iy/(10*Ax*L)          0       -L^2/140-Iy/30/Ax                 0              ;...
%           0    -13*L/420+Iz/(10*Ax*L)             0                       0                 0                -L^2/140-Iz/30/Ax     ;];
% %       
% M_Rod =Rhoi*Ax*L* [M_ii   M_ij;...
%                    M_ji   M_jj;];
%% Timoshenko 梁
% M_Rod =Rhoi*Ax_i*L/6* [ 2    0      0        0            0             0         1      0     0       0            0               0      ;...
%                         0    2      0        0            0             0         0      1     0       0            0               0      ;...
%                         0    0      2        0            0             0         0      0     1       0            0               0      ;...
%                         0    0      0    2*Ix/Ax_i        0             0         0      0     0    Ix/Ax_i         0               0      ;...
%                         0    0      0        0      2*Ax_i*L/35         0         0      0     0       0      -3*Ax_i*L/70          0      ;...
%                         0    0      0        0            0        2*Ax_i*L/35    0      0     0       0            0         -3*Ax_i*L/70 ;...
%                         1    0      0        0            0             0         2      0     0       0            0               0      ;...
%                         0    1      0        0            0             0         0      2     0       0            0               0      ;...
%                         0    0      1        0            0             0         0      0     2       0            0               0      ;...
%                         0    0      0     Ix/Ax_i         0             0         0      0     0   2*Ix/Ax_i        0               0      ;...
%                         0    0      0        0      -3*Ax_i*L/70        0         0      0     0       0       2*Ax_i*L/35          0      ;...
%                         0    0      0        0            0       -3*Ax_i*L/70    0      0     0       0            0          2*Ax_i*L/35 ;];
% 
% M_Rod =Rhoi*Ax_i*L/6* [ 2    0      0        0            0             0         1      0     0       0            0               0      ;...
%                         0    2      0        0            0             0         0      1     0       0            0               0      ;...
%                         0    0      2        0            0             0         0      0     1       0            0               0      ;...
%                         0    0      0    2*Ix/Ax_i        0             0         0      0     0    Ix/Ax_i         0               0      ;...
%                         0    0      0        0            0             0         0      0     0       0            0               0      ;...
%                         0    0      0        0            0             0         0      0     0       0            0               0      ;...
%                         1    0      0        0            0             0         2      0     0       0            0               0      ;...
%                         0    1      0        0            0             0         0      2     0       0            0               0      ;...
%                         0    0      1        0            0             0         0      0     2       0            0               0      ;...
%                         0    0      0     Ix/Ax_i         0             0         0      0     0   2*Ix/Ax_i        0               0      ;...
%                         0    0      0        0            0             0         0      0     0       0            0               0      ;...
%                         0    0      0        0            0             0         0      0     0       0            0               0      ;];
%% 坐标变换
M_Rod = RT'*M_Rod * RT ;         % 结构坐标系按下的质量矩阵
end
