%% 空间桁架结构——【单元坐标系】下杆件刚度
%% 输入：杆件编号【其它参数由全局变量读取】
%% 输出：杆件刚度——结构坐标系
function S_Rod = SpaceFrame_StiffnessMatrix_Rod(NUM_Cell_Rod)

global Ax Inertia_moment Elastic_modulus Shear_modulus Density
global Coordinate_Cell_Node Coordinate_Cell_Rod
global Length_X Length_Y Length_Z Ax m_Tip J_Tip

%% 杆件节点坐标及坐标变换矩阵
NUM_Node = Coordinate_Cell_Rod(NUM_Cell_Rod,:);     % 读取杆件编号所对应杆的节点编号
pj = Coordinate_Cell_Node(NUM_Node(1),:) ;        % 杆件的节点坐标读取
pk = Coordinate_Cell_Node(NUM_Node(2),:) ;        % 杆件的节点坐标读取

xm = pk-pj; %xm轴的方向向量
c = sqrt(xm(1)^2+xm(3)^2);
if c > 0.0001
    zm = [-xm(3) 0 xm(1);];  % zm轴的方向向量——倾斜杆
else
    zm = [0 0 1;];           % zm轴的方向向量——垂直杆
end

ym = cross(zm,xm);                           % ym轴的方向向量
R =[xm/norm(xm); ym/norm(ym); zm/norm(zm);]; % 坐标变换矩阵——全局坐标系到杆件坐标系

RT = [     R      zeros(3)     zeros(3)     zeros(3);...
       zeros(3)      R         zeros(3)     zeros(3);...
       zeros(3)   zeros(3)        R         zeros(3);...
       zeros(3)   zeros(3)     zeros(3)        R    ;];

L = norm(xm);
E = Elastic_modulus;
G = Shear_modulus;
Ix= Inertia_moment(1,1);
Iy= Inertia_moment(2,1);
Iz= Inertia_moment(3,1);

%% Eular-Bernoulli梁  /  瑞丽梁
k_ii = [ E*Ax/L        0             0           0          0            0    ;...
           0     12*E*Iz/L^3         0           0          0       6*E*Iz/L^2;...
           0           0       12*E*Iy/L^3       0     -6*E*Iy/L^2       0    ;...
           0           0             0        G*Ix/L        0            0    ;...
           0           0         -6*E*Iy/L^2     0      4*E*Iy/L         0    ;...
           0       6*E*Iz/L^2        0           0          0        4*E*Iz/L ;];

k_jj = [ E*Ax/L        0             0           0          0            0    ;...
           0     12*E*Iz/L^3         0           0          0      -6*E*Iz/L^2;...
           0           0       12*E*Iy/L^3       0      6*E*Iy/L^2       0    ;...
           0           0             0        G*Ix/L        0            0    ;...
           0           0        6*E*Iy/L^2       0      4*E*Iy/L         0    ;...
           0      -6*E*Iz/L^2        0           0          0        4*E*Iz/L ;];

k_ij = [-E*Ax/L        0             0           0          0            0    ;...
           0    -12*E*Iz/L^3         0           0          0       6*E*Iz/L^2;...
           0           0      -12*E*Iy/L^3       0     -6*E*Iy/L^2       0    ;...
           0           0             0       -G*Ix/L        0            0    ;...
           0           0          6*E*Iy/L^2     0      2*E*Iy/L         0    ;...
           0      -6*E*Iz/L^2        0           0          0        2*E*Iz/L ;];
         
k_ji = [-E*Ax/L        0             0           0          0            0    ;...
           0    -12*E*Iz/L^3         0           0          0      -6*E*Iz/L^2;...
           0           0      -12*E*Iy/L^3       0      6*E*Iy/L^2       0    ;...
           0           0             0       -G*Ix/L        0            0    ;...
           0           0         -6*E*Iy/L^2     0      2*E*Iy/L         0    ;...
           0       6*E*Iz/L^2        0           0          0        2*E*Iz/L ;];

%% Timoshenko梁 （考虑剪切变形）
% % 圆管的形状系数
% k = 24*(1+(D_out/D_in)^2)^2*(1+poisson_ratio)^2/...                              % 截面的剪切形状系数-
%     ( (1+(D_out/D_in)^2)^2*(32*poisson_ratio^2 + 56*poisson_ratio+28) + ...
%       (D_out/D_in)^2*(76*poisson_ratio^2 + 196*poisson_ratio +107)          );
% % 矩形梁的形状系数
% k = 5/6 + Length_Z^2/Length_Y^2;                             % 截面的剪切形状系数-
% 
% Phi_y = 12*E*Iz/(G*Ax*L^2)/k;
% Phi_z = 12*E*Iy/(G*Ax*L^2)/k;
% 
% k_ii = [ E*Ax/L              0                    0                    0                    0                         0                ;...
%            0     12*E*Iz/(1+Phi_y)/L^3            0                    0                    0                6*E*Iz/(1+Phi_y)/L^2      ;...
%            0                0             12*E*Iy/(1+Phi_z)/L^3        0          -6*E*Iy/(1+Phi_z)/L^2               0                ;...
%            0                0                     0                  G*Ix/L                 0                         0                ;...
%            0                0             -6*E*Iy/(1+Phi_z)/L^2        0      (4+Phi_z)*E*Iy/(1+Phi_z)/L              0                ;...
%            0      6*E*Iz/(1+Phi_y)/L^2            0                    0                    0            (4+Phi_y)*E*Iz/(1+Phi_y)/L ;] ;
% 
% k_jj = [ E*Ax/L              0                    0                    0                    0                         0                ;...
%            0     12*E*Iz/(1+Phi_y)/L^3            0                    0                    0               -6*E*Iz/(1+Phi_y)/L^2      ;...
%            0                0             12*E*Iy/(1+Phi_z)/L^3        0           6*E*Iy/(1+Phi_z)/L^2               0                ;...
%            0                0                     0                  G*Ix/L                 0                         0                ;...
%            0                0              6*E*Iy/(1+Phi_z)/L^2        0      (4+Phi_z)*E*Iy/(1+Phi_z)/L              0                ;...
%            0     -6*E*Iz/(1+Phi_y)/L^2            0                    0                    0            (4+Phi_y)*E*Iz/(1+Phi_y)/L ;] ;
% 
% 
% k_ij = [-E*Ax/L              0                    0                    0                    0                         0                ;...
%            0    -12*E*Iz/(1+Phi_y)/L^3            0                    0                    0                6*E*Iz/(1+Phi_y)/L^2      ;...
%            0                0            -12*E*Iy/(1+Phi_z)/L^3        0          -6*E*Iy/(1+Phi_z)/L^2               0                ;...
%            0                0                     0                 -G*Ix/L                 0                         0                ;...
%            0                0              6*E*Iy/(1+Phi_z)/L^2        0      (2-Phi_z)*E*Iy/(1+Phi_z)/L              0                ;...
%            0     -6*E*Iz/(1+Phi_y)/L^2            0                    0                    0            (2-Phi_y)*E*Iz/(1+Phi_y)/L ;] ;
%          
% k_ji = [-E*Ax/L              0                    0                    0                    0                         0                ;...
%            0    -12*E*Iz/(1+Phi_y)/L^3            0                    0                    0               -6*E*Iz/(1+Phi_y)/L^2      ;...
%            0                0            -12*E*Iy/(1+Phi_z)/L^3        0           6*E*Iy/(1+Phi_z)/L^2               0                ;...
%            0                0                     0                 -G*Ix/L                 0                         0                ;...
%            0                0             -6*E*Iy/(1+Phi_z)/L^2        0      (2-Phi_z)*E*Iy/(1+Phi_z)/L              0                ;...
%            0      6*E*Iz/(1+Phi_y)/L^2            0                    0                    0            (2-Phi_y)*E*Iz/(1+Phi_y)/L ;] ;
%       
%% ------------------------------------------------------------------------------------
%% 预应力刚度矩阵
Pre_Stress = -( (Length_X-(pk(:,1)+pj(:,1))/2)*Ax*Density + m_Tip )*9.8;  % 考虑重力作用下的刚度非线性项
% % Pre_Stress = -m_Tip*9.8;         % 忽略重力作用下的刚度非线性项
% Pre_Stress = 0;         % 忽略重力作用下的刚度非线性项
k0_ii =-Pre_Stress/L*[ 0      0     0        0           0         0   ;...
                       0     6/5    0        0           0       L/10  ;...
                       0      0    6/5       0         -L/10       0   ;...
                       0      0     0    (Iy+Iz)/Ax      0         0   ;...
                       0      0   -L/10      0        2*L^2/15     0   ;...
                       0    L/10    0        0           0     2*L^2/15;];

k0_jj =-Pre_Stress/L*[ 0      0     0         0          0         0   ;...
                       0     6/5    0         0          0       -L/10  ;...
                       0      0    6/5        0         L/10       0   ;...
                       0      0     0     (Iy+Iz)/Ax     0         0   ;...
                       0      0    L/10       0       2*L^2/15     0   ;...
                       0   -L/10    0         0          0     2*L^2/15;];
                   
k0_ij =-Pre_Stress/L*[ 0      0     0         0          0         0   ;...
                       0    -6/5    0         0          0       L/10  ;...
                       0      0   -6/5        0        -L/10       0   ;...
                       0      0     0    -(Iy+Iz)/Ax     0         0   ;...
                       0      0    L/10       0        -L^2/30     0   ;...
                       0   -L/10    0         0          0      -L^2/30;];
         
k0_ji =-Pre_Stress/L*[ 0      0     0         0          0        0   ;...
                       0    -6/5    0         0          0     -L/10  ;...
                       0      0   -6/5        0         L/10      0   ;...
                       0      0     0    -(Iy+Iz)/Ax     0        0   ;...
                       0      0   -L/10       0       -L^2/30     0   ;...
                       0    L/10    0         0          0     -L^2/30;];

%% ------------------------------------------------------------------------
% 总的刚度矩阵
S_Rod = [k_ii+k0_ii   k_ij+k0_ij;...
         k_ji+k0_ji   k_jj+k0_jj;];
%% 刚度的坐标转换
S_Rod = RT'*S_Rod*RT;              % 杆件坐标系到结构坐标系
end